// Generated by `wit-bindgen` 0.55.0. DO NOT EDIT!
// Options used:
pub type AgentAction = fairexchange::unified::types::AgentAction;
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_init_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,) { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();{
  let len0 = arg1;
  T_::init(<_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0)))
};
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_process_message_cabi<T_: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result1 = {
  T_::process_message(match arg0 {
    0 => None,
    1 => {
      let e = {
        let len0 = arg2;

        <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg1.cast(), len0, len0))
      };
      Some(e)
    }
    _ => _rt::invalid_enum_discriminant(),
  })
};
let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
use fairexchange::unified::types::AgentAction as V7;
match result1 {
  V7::SendToPeer(e) => {
    *ptr2.add(0).cast::<u8>() = (0i32) as u8;
    let vec3 = <_ as Into<_rt::Vec<_>>>::into(e).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
  },
  V7::SendToTtp(e) => {
    *ptr2.add(0).cast::<u8>() = (1i32) as u8;
    let vec4 = <_ as Into<_rt::Vec<_>>>::into(e).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
  },
  V7::WaitForPeer=> {
    {
      *ptr2.add(0).cast::<u8>() = (2i32) as u8;
    }
  }
  V7::CompleteSuccess(e) => {
    *ptr2.add(0).cast::<u8>() = (3i32) as u8;
    let vec5 = (e.into_bytes()).into_boxed_slice();
    let ptr5 = vec5.as_ptr().cast::<u8>();
    let len5 = vec5.len();
    ::core::mem::forget(vec5);
    *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
  },
  V7::CompleteFailure(e) => {
    *ptr2.add(0).cast::<u8>() = (4i32) as u8;
    let vec6 = (e.into_bytes()).into_boxed_slice();
    let ptr6 = vec6.as_ptr().cast::<u8>();
    let len6 = vec6.len();
    ::core::mem::forget(vec6);
    *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
  },
}
ptr2
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_process_message<T_: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = i32::from(*arg0.add(0).cast::<u8>());
  match l0 {
    0 => {
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base3 = l1;
      let len3 = l2;
      _rt::cabi_dealloc(base3, len3 * 1, 1);
    },
    1 => {
      let l4 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l5 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base6 = l4;
      let len6 = l5;
      _rt::cabi_dealloc(base6, len6 * 1, 1);
    },
    2 => (),
    3 => {
      let l7 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l8 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l7, l8, 1);
    },
    _ => {
      let l9 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
      let l10 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
      _rt::cabi_dealloc(l9, l10, 1);
    },
  }
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn init(config: _rt::Vec::<u8>,) -> ();
  #[allow(async_fn_in_trait)]
  fn process_message(incoming: Option<_rt::Vec::<u8>>,) -> AgentAction;
}
#[doc(hidden)]

macro_rules! __export_world_unified_agent_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "init")]
    unsafe extern "C" fn export_init(arg0: *mut u8,arg1: usize,) {
      unsafe { $($path_to_types)*::_export_init_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "process-message")]
    unsafe extern "C" fn export_process_message(arg0: i32,arg1: *mut u8,arg2: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_process_message_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_process-message")]
    unsafe extern "C" fn _post_return_process_message(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_process_message::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_unified_agent_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
#[allow(dead_code, clippy::all)]
pub mod fairexchange {
  pub mod unified {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[derive(Clone)]
      pub enum AgentAction {
        SendToPeer(_rt::Vec::<u8>),
        SendToTtp(_rt::Vec::<u8>),
        WaitForPeer,
        CompleteSuccess(_rt::String),
        CompleteFailure(_rt::String),
      }
      impl ::core::fmt::Debug for AgentAction {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            AgentAction::SendToPeer(e) => {
              f.debug_tuple("AgentAction::SendToPeer").field(e).finish()
            }
            AgentAction::SendToTtp(e) => {
              f.debug_tuple("AgentAction::SendToTtp").field(e).finish()
            }
            AgentAction::WaitForPeer => {
              f.debug_tuple("AgentAction::WaitForPeer").finish()
            }
            AgentAction::CompleteSuccess(e) => {
              f.debug_tuple("AgentAction::CompleteSuccess").field(e).finish()
            }
            AgentAction::CompleteFailure(e) => {
              f.debug_tuple("AgentAction::CompleteFailure").field(e).finish()
            }
          }
        }
      }

    }

  }
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::vec::Vec;
  pub use alloc_crate::string::String;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_unified_agent_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_unified_agent_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_unified_agent_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.55.0:fairexchange:unified:unified-agent:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 420] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa0\x02\x01A\x02\x01\
A\x0a\x01B\x03\x01p}\x01q\x05\x0csend-to-peer\x01\0\0\x0bsend-to-ttp\x01\0\0\x0d\
wait-for-peer\0\0\x10complete-success\x01s\0\x10complete-failure\x01s\0\x04\0\x0c\
agent-action\x03\0\x01\x03\0\x1afairexchange:unified/types\x05\0\x02\x03\0\0\x0c\
agent-action\x03\0\x0cagent-action\x03\0\x01\x01p}\x01@\x01\x06config\x03\x01\0\x04\
\0\x04init\x01\x04\x01k\x03\x01@\x01\x08incoming\x05\0\x02\x04\0\x0fprocess-mess\
age\x01\x06\x04\0\"fairexchange:unified/unified-agent\x04\0\x0b\x13\x01\0\x0duni\
fied-agent\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070\
.246.2\x10wit-bindgen-rust\x060.55.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

